enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  14d8e410-b64b-4a2d-93de-c360d232de1d:
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
